### ISSUE TITLE
Cron is not a function

### ISSUE THREAD

**Issue by MyWay** [towfiqi/serpbear#247]
Hi, I'm running v2.0.5 on Docker and I'm getting the following error at start:

```
[1] /app/cron.js:109
[1]    Cron(failedCronTime, () => {
[1]    ^
[1] 
[1] TypeError: Cron is not a function
[1]     at runAppCronJobs (/app/cron.js:109:4)
[1]     at Object.<anonymous> (/app/cron.js:151:1)
[1]     at Module._compile (node:internal/modules/cjs/loader:1546:14)
[1]     at Object..js (node:internal/modules/cjs/loader:1689:10)
[1]     at Module.load (node:internal/modules/cjs/loader:1318:32)
[1]     at Function._load (node:internal/modules/cjs/loader:1128:12)
[1]     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
[1]     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
[1]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
[1]     at node:internal/main/run_main_module:36:49

```

**Comment by quick-tutoriel** [comment]
Hello,
since V2.04 I also get this error at startup.
Is it possible to correct it?
Thanks
