### ISSUE TITLE
TypeError: domain.trim(...).replaceAll is not a function

### ISSUE THREAD

**Issue by marko-fedorenko** [towfiqi/serpbear#27]
I am running locally and when I try to add the first domain I am getting an error: Error Adding New Domain
![image](https://user-images.githubusercontent.com/78041242/206298905-b131a331-3ced-4be8-84e1-76674ecdd8e7.png)
In the console there is an error: domain.trim(...).replaceAll is not a function
![image](https://user-images.githubusercontent.com/78041242/206299049-35f0c710-8765-4fef-a836-c9fec363e85c.png)
``[start] POST /api/domains
[start] TypeError: domain.trim(...).replaceAll is not a function
[start]     at addDomain (C:\GitHub\serpbear\.next\server\pages\api\domains.js:112:29)
[start]     at handler (C:\GitHub\serpbear\.next\server\pages\api\domains.js:77:16)
[start]     at async Object.apiResolver (C:\GitHub\serpbear\node_modules\next\dist\server\api-utils\node.js:366:9)
[start]     at async NextNodeServer.runApi (C:\GitHub\serpbear\node_modules\next\dist\server\next-server.js:481:9)
[start]     at async Object.fn (C:\GitHub\serpbear\node_modules\next\dist\server\next-server.js:735:37)
[start]     at async Router.execute (C:\GitHub\serpbear\node_modules\next\dist\server\router.js:247:36)
[start]     at async NextNodeServer.run (C:\GitHub\serpbear\node_modules\next\dist\server\base-server.js:347:29)
[start]     at async NextNodeServer.handleRequest (C:\GitHub\serpbear\node_modules\next\dist\server\base-server.js:285:20)``
How can I fix this problem?

**Comment by marko-fedorenko** [comment]
you're right, thanks so much!
