### ISSUE TITLE
Error while refreshing keywords using ScrapingRobot 

### ISSUE THREAD

**Issue by leonguyen52** [towfiqi/serpbear#29]
I updated token from ScrapingRobot to setting and saved successfully. However when I refreshed the keyword ranking, it showing error "Error Refreshing Keywords."

I also checked the database file, it's set with permission 644 and owned by mysql. I'm running SerpBear on Docker version.
Logs:
[0] getKeywords:  6
[0] GET /api/settings
[0] GET /api/settings
[0] PUT /api/settings
[0] GET /api/settings
[0] POST /api/refresh?id=all&domain=xx.com
[0] keywordIDs:  false
[0] ERROR refresThehKeywords:  Error
[0]     at Database.<anonymous> (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:179:27)
[0]     at /app/node_modules/sequelize/lib/dialects/sqlite/query.js:177:50
[0]     at new Promise (<anonymous>)
[0]     at Query.run (/app/node_modules/sequelize/lib/dialects/sqlite/query.js:177:12)
[0]     at /app/node_modules/sequelize/lib/sequelize.js:314:28
[0]     at async SQLiteQueryInterface.bulkUpdate (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:366:12)
[0]     at async Keyword.update (/app/node_modules/sequelize/lib/model.js:1958:28)
[0]     at async refresTheKeywords (/app/.next/server/chunks/816.js:76:9)
[0]     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
[0]     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9) {
[0]   name: 'SequelizeDatabaseError',
[0]   parent: [Error: SQLITE_READONLY: attempt to write a readonly database] {
[0]     errno: 8,
[0]     code: 'SQLITE_READONLY',
[0]     sql: 'UPDATE `keyword` SET `updating`=$1 WHERE `domain` = $2'
[0]   },
[0]   original: [Error: SQLITE_READONLY: attempt to write a readonly database] {
[0]     errno: 8,
[0]     code: 'SQLITE_READONLY',
[0]     sql: 'UPDATE `keyword` SET `updating`=$1 WHERE `domain` = $2'
[0]   },
[0]   sql: 'UPDATE `keyword` SET `updating`=$1 WHERE `domain` = $2',
[0]   parameters: {}
[0] }

**Comment by towfiqi** [comment]
How are you mapping the data folder of the app with Docker? Did you follow the instruction posted in the docs? If you are using docker, its best to create a volume and map that volume to app's data folder.
