### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by vontainment** [towfiqi/serpbear#49]
I keep getting this error when loading a domain

Application error: a client-side exception has occurred (see the browser console for more information).

`framework-4556c45dd113b893.js:1 TypeError: Cannot read properties of undefined (reading '0')
    at S ([slug]-a1a343edda569643.js:1:18290)
    at Eo (framework-4556c45dd113b893.js:1:63192)
    at xi (framework-4556c45dd113b893.js:1:120432)
    at bs (framework-4556c45dd113b893.js:1:109368)
    at gs (framework-4556c45dd113b893.js:1:109296)
    at vs (framework-4556c45dd113b893.js:1:109159)
    at as (framework-4556c45dd113b893.js:1:105939)
    at ls (framework-4556c45dd113b893.js:1:104490)
    at S (framework-4556c45dd113b893.js:1:138450)
    at MessagePort.T (framework-4556c45dd113b893.js:1:138984)
du @ framework-4556c45dd113b893.js:1
a.componentDidCatch.t.callback @ framework-4556c45dd113b893.js:1
Ua @ framework-4556c45dd113b893.js:1
ki @ framework-4556c45dd113b893.js:1
bi @ framework-4556c45dd113b893.js:1
yi @ framework-4556c45dd113b893.js:1
(anonymous) @ framework-4556c45dd113b893.js:1
ws @ framework-4556c45dd113b893.js:1
ls @ framework-4556c45dd113b893.js:1
S @ framework-4556c45dd113b893.js:1
T @ framework-4556c45dd113b893.js:1
main-d360cca81814416b.js:1 TypeError: Cannot read properties of undefined (reading '0')
    at S ([slug]-a1a343edda569643.js:1:18290)
    at Eo (framework-4556c45dd113b893.js:1:63192)
    at xi (framework-4556c45dd113b893.js:1:120432)
    at bs (framework-4556c45dd113b893.js:1:109368)
    at gs (framework-4556c45dd113b893.js:1:109296)
    at vs (framework-4556c45dd113b893.js:1:109159)
    at as (framework-4556c45dd113b893.js:1:105939)
    at ls (framework-4556c45dd113b893.js:1:104490)
    at S (framework-4556c45dd113b893.js:1:138450)
    at MessagePort.T (framework-4556c45dd113b893.js:1:138984)
J @ main-d360cca81814416b.js:1
fn @ main-d360cca81814416b.js:1
value @ main-d360cca81814416b.js:1
a.componentDidCatch.t.callback @ framework-4556c45dd113b893.js:1
Ua @ framework-4556c45dd113b893.js:1
ki @ framework-4556c45dd113b893.js:1
bi @ framework-4556c45dd113b893.js:1
yi @ framework-4556c45dd113b893.js:1
(anonymous) @ framework-4556c45dd113b893.js:1
ws @ framework-4556c45dd113b893.js:1
ls @ framework-4556c45dd113b893.js:1
S @ framework-4556c45dd113b893.js:1
T @ framework-4556c45dd113b893.js:1
main-d360cca81814416b.js:1 `

**Comment by vontainment** [comment]
I've also seen an error in the console of the docker container about the Java heap stack running out of memory
