### ISSUE TITLE
[ERROR] Scraping Keyword : keyword . Error: undefined

### ISSUE THREAD

**Issue by Aviortheking** [towfiqi/serpbear#52]
It seems that when the scrapper run automatically it does fail everytime (see error below)

while it does work when I use the `Reload all serps` button

```
2023-01-04T00:00:04.809088677Z [0] [ERROR] Scraping Keyword : prototypage . Error: undefined
2023-01-04T00:00:04.813572276Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.813566428Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.813560558Z [0] at async Promise.all (index 23)
2023-01-04T00:00:04.813554415Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.813548988Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.813543393Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.813535533Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.813487460Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.817945102Z [0] [ERROR] Scraping Keyword : bureau d'étude conception produit . Error: undefined
2023-01-04T00:00:04.818496502Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.818491117Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.818485922Z [0] at async Promise.all (index 67)
2023-01-04T00:00:04.818480662Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.818475516Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.818469139Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.818461881Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.818445803Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.820810650Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.820805022Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.820799317Z [0] at async Promise.all (index 66)
2023-01-04T00:00:04.820793882Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.820788207Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.820782610Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.820775800Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.820759437Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.820391384Z [0] [ERROR] Scraping Keyword : atelier idéation . Error: undefined
2023-01-04T00:00:04.822995197Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.822990135Z [0] at async Promise.all (index 56)
2023-01-04T00:00:04.822984852Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.822979587Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.822972042Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.822941269Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.822925722Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.822576326Z [0] [ERROR] Scraping Keyword : grossiste 3d . Error: undefined
2023-01-04T00:00:04.823000623Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.826465393Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.826460064Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.826454786Z [0] at async Promise.all (index 51)
2023-01-04T00:00:04.826449946Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.826444442Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.826439503Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.826432386Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.826417739Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.826007167Z [0] [ERROR] Scraping Keyword : grossiste filament 3d . Error: undefined
2023-01-04T00:00:04.828826936Z [0] [ERROR] Scraping Keyword : formation fab manager . Error: undefined
2023-01-04T00:00:04.829277368Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.829271777Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.829266561Z [0] at async Promise.all (index 15)
2023-01-04T00:00:04.829260977Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.829255455Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.829250194Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.829242818Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.829228094Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.831606344Z [0] [ERROR] Scraping Keyword : industrialisation . Error: undefined
2023-01-04T00:00:04.832104510Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.832099019Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.832092130Z [0] at async Promise.all (index 25)
2023-01-04T00:00:04.832062123Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.832056512Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.832051493Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.832044354Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.832028843Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.833975443Z [0] [ERROR] Scraping Keyword : pokemon cards . Error: undefined
2023-01-04T00:00:04.834430059Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.834424624Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.834419342Z [0] at async Promise.all (index 74)
2023-01-04T00:00:04.834414597Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.834410053Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.834404657Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.834398154Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.834382867Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.840817363Z [0] [ERROR] Scraping Keyword : filament overture . Error: undefined
2023-01-04T00:00:04.841591769Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.841586486Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.841581349Z [0] at async Promise.all (index 53)
2023-01-04T00:00:04.841576111Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.841570642Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.841565137Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.841558256Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.841542316Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.865995159Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.865945882Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.865399768Z [0] [ERROR] Scraping Keyword : pokemon jcc cartes . Error: undefined
2023-01-04T00:00:04.866057694Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.866027274Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.866022342Z [0] at async Promise.all (index 85)
2023-01-04T00:00:04.866016993Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.866011779Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.866006388Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.868940590Z [0] [ERROR] Scraping Keyword : filament flexible . Error: undefined
2023-01-04T00:00:04.869384461Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.869373398Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.869368094Z [0] at async Promise.all (index 45)
2023-01-04T00:00:04.869362598Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.869357583Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.869351901Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.869344580Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.869325480Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.871419632Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.871413472Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.871408189Z [0] at async Promise.all (index 108)
2023-01-04T00:00:04.871402857Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.871397689Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.871392187Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.871385332Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.871369593Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.871013166Z [0] [ERROR] Scraping Keyword : api pokemon fr . Error: undefined
2023-01-04T00:00:04.873996507Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.873977717Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.873701957Z [0] [ERROR] Scraping Keyword : petg prusament . Error: undefined
2023-01-04T00:00:04.874033323Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.874027703Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.874022119Z [0] at async Promise.all (index 59)
2023-01-04T00:00:04.874016589Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.874010318Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.874004147Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.876043309Z [0] [ERROR] Scraping Keyword : electronique . Error: undefined
2023-01-04T00:00:04.877862637Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.877858751Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.877854879Z [0] at async Promise.all (index 38)
2023-01-04T00:00:04.877850262Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.877831166Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.877827211Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.877821501Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.877802954Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.882900453Z [0] [ERROR] Scraping Keyword : petg transparent . Error: undefined
2023-01-04T00:00:04.882215921Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.882211023Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.882206559Z [0] at async Promise.all (index 88)
2023-01-04T00:00:04.882201244Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.882196577Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.882191611Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.882185666Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.882178023Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.882131579Z [0] [ERROR] Scraping Keyword : pokemon cartes . Error: undefined
2023-01-04T00:00:04.883257618Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.883252364Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.883246999Z [0] at async Promise.all (index 60)
2023-01-04T00:00:04.883241554Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.883235825Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.883230437Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.883222560Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.883169042Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.886719984Z [0] at async refreshAndUpdateKeywords (/app/.next/server/chunks/816.js:110:23)
2023-01-04T00:00:04.886716082Z [0] at async refreshKeywords (/app/.next/server/chunks/816.js:229:28)
2023-01-04T00:00:04.886711904Z [0] at async Promise.all (index 100)
2023-01-04T00:00:04.886695006Z [0] at async scrapeKeywordFromGoogle (/app/.next/server/chunks/816.js:372:87)
2023-01-04T00:00:04.886687437Z [0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-01-04T00:00:04.886663250Z [0] at Response.json (node:internal/deps/undici/undici:6160:23)
2023-01-04T00:00:04.886658304Z [0] at JSON.parse (<anonymous>)
2023-01-04T00:00:04.886645102Z [0] [ERROR_MESSAGE]: SyntaxError: Unexpected token B in JSON at position 0
2023-01-04T00:00:04.886223812Z [0] [ERROR] Scraping Keyword : retroconception 3d nantes . Error: undefined 
```

**Comment by balonchiks** [comment]
having exactly the same issue

**Comment by andresledo** [comment]
Same issue

![Captura](https://user-images.githubusercontent.com/44968815/211361539-4ed808b1-2dff-4871-9074-5252673b9708.PNG)

**Comment by andresledo** [comment]
> @andresledo Does this also happen when you manually refresh the keyword from the ui?

Yes, but I have restarted the container and not anymore. Let's see if everything is updated correctly at night.

**Comment by Aviortheking** [comment]
> @andresledo Does this also happen when you manually refresh the keyword from the ui?

It does not happens when manually refreshing from the UI for me

**Comment by towfiqi** [comment]
@Aviortheking Can you please let me know how you are running the app? locally with docker? or fly.io? 

Can you please open the `failed_queue.json` inside the data direcory of the serpbear directory and share the content of that file?

**Comment by Aviortheking** [comment]
I am running it in a docker image

failed_queue.json contains an empty array
```
/app/data $ cat failed_queue.json 
[]/app/data $ 

```

**Comment by towfiqi** [comment]
@Aviortheking  Are you using ScrapingAnt? Can you please switch to Scraping Robot and see if that fixes the issue?

**Comment by Aviortheking** [comment]
yep I can try this

**Comment by balonchiks** [comment]
> @Aviortheking  Are you using ScrapingAnt? Can you please switch to Scraping Robot and see if that fixes the issue?

Was using scrapingAnt and switched to robot yesterday - all seems to work fine now. All the keywords I had were updated by cron at midnight successfully

**Comment by Aviortheking** [comment]
Still happening on latest version but know also happens with manual scrap

Still trying to make Scrapping robot work

**Comment by Aviortheking** [comment]
@towfiqi It also happens with Scrapping robot

**Comment by towfiqi** [comment]
@Aviortheking This actually could be a memory leak issue of node-cron. Can you please restart the app and see if the issue reappears?

**Comment by Aviortheking** [comment]
I don't really know I restarted the app and even moved it to another server and I still encounter the same error 😢

**Comment by towfiqi** [comment]
@Aviortheking You are running it with docker right? How much memory areou allocating for the instance?

**Comment by Aviortheking** [comment]
31 GB xd

**Comment by skrypt-nl** [comment]
I'm encountering a similar error:

```
[start] [ERROR] Scraping Keyword :  SEO . Error:  undefined
[start] [ERROR_MESSAGE]:  Error: [object Object]
[start]     at scrapeKeywordFromGoogle (/Users/user/serpbear/.next/server/chunks/816.js:390:19)
[start]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[start]     at async Promise.all (index 2)
[start]     at async refreshKeywords (/Users/user/serpbear/.next/server/chunks/816.js:229:28)
[start]     at async refreshAndUpdateKeywords (/Users/user/serpbear/.next/server/chunks/816.js:110:23)
```

I'm using ScrapingAnt (free trial) and I'm running the latest version of SerpBear locally on MacOS 13.2.1, with Node v16.19.1. The dashboard also says `scrapingant: This domain is not allowed for free subscription. Please, subscribe to the paid plan for using it. Please check out the documentation: https://docs.scrapingant.com/`.

**Comment by towfiqi** [comment]
ScrapingAnt Free does not work anymore. Please see #78
